version: '3.8'

services:
  auth-service:
    container_name: auth-service
    image: auth-service:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: yarn pm2-runtime start ./dist/main.js -i max
    ports:
      - 2327:3000
    env_file:
      - .env.prod
    volumes:
      - ./secrets:/usr/src/app/secrets
    restart: unless-stopped

