version: '3.8'

services:
    auth-service:
        container_name: auth-service
        image: auth-service:1.0.0
        build:
            context: .
            dockerfile: ./Dockerfile
        command: npm run start:dev
        ports:
            - 2326:3000
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        env_file:
            -   .env.staging
        restart: unless-stopped
